BYOBU_DARK="\#444444"
BYOBU_LIGHT="\#EEEEEE"
BYOBU_ACCENT="\#F9C6D7"
BYOBU_HIGHLIGHT="\#FB6F92"
MONOCHROME=

##########
# jakku
##########
#BYOBU_DARK="\#FF964F"
#BYOBU_LIGHT=black
#BYOBU_ACCENT="\#FB6F92"
#BYOBU_HIGHLIGHT="\#F9C6D7"
#MONOCHROME=

##########
# lorrd
##########
#BYOBU_DARK="\#e74163"
#BYOBU_LIGHT=black
#BYOBU_ACCENT=magenta
#BYOBU_HIGHLIGHT=pink
#MONOCHROME=

