[window]
padding.x = 5
padding.y = 5
dimensions.columns = 220
dimensions.lines = 30
opacity = 0.9
blur = true
option_as_alt = "Both"

[font]
normal.family = "Consolas"
size = 14

# Default colors
[colors.primary]
background = '#1e1e1e'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black      = '#171421'
red        = '#c01c28'
green      = '#26a269'
yellow     = '#a2734c'
blue       = '#12488b'
magenta    = '#a347ba'
cyan       = '#2aa1b3'
white      = '#d0cfcc'

# Bright colors
[colors.bright]
black      = '#5e5c64'
red        = '#f66151'
green      = '#33d17a'
yellow     = '#e9ad0c'
blue       = '#2a7bde'
magenta    = '#c061cb'
cyan       = '#33c7de'
white      = '#ffffff'

